apiVersion: v1
kind: Service
metadata:
  name: portal-service
spec:
  selector:
    app.kubernetes.io/name: portal-deployment
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer